---
- import_playbook: includes/ensure_host_keys.yml

- name: VOLTTRON Status
  hosts: all
  tasks:
    - include_tasks: includes/common.yml

    - name: Retrieving Status
      volttron_instance_config:
        config_file: "{{ host_config }}"
      check_mode: True
      register: instance_state

    - debug:
        var: instance_state
