---
- import_playbook: includes/ensure_host_keys.yml

- name: Stop VOLTTRON
  hosts: all
  tasks:
    - include_tasks: includes/common.yml
    - name: Configure VOLTTRON Instances
      volttron_instance_config:
        config_file: "{{ host_config }}"
        state: "STOPPED"
        phase: "NONE"
      register: instance_state

    - debug:
        var: instance_state
