---
all:
    hosts:
        web:
            ansible_host: 192.168.44.10
            ansible_user: vagrant
            enable_web: yes
        collector1:
            ansible_host: 192.168.44.11
            ansible_user: vagrant
            message_bus: rmq
            enable_drivers: yes
        collector2:
            ansible_host: 192.168.44.12
            ansible_user: vagrant
            enable_drivers: yes
