---
all:
    hosts:
        web:
            ansible_host: 192.168.44.10
            enable_web: yes
        collector1:
            ansible_host: 192.168.44.11
            message_bus: rmq
            enable_drivers: yes
        collector2:
            ansible_host: 192.168.44.12
            enable_drivers: yes
    vars:
        ansible_user: vagrant
