---
- name: Set default values
  set_fact:
    ansible_python_interpreter: /usr/bin/python3
    ## variables related to the version of volttron to be installed
    volttron_git_organization: "{{ volttron_git_organization | default('volttron') }}"
    volttron_git_repo: "{{ volttron_git_repo | default('volttron') }}"
    volttron_git_branch: "{{ volttron_git_branch | default('develop') }}"
    ## variables related to where volttron source and state are placed on the node
    volttron_home: "{{ volttron_home | default('{{ ansible_env.HOME }}/.volttron') }}"
    volttron_root: "{{ volttron_root | default('{{ ansible_env.HOME }}/volttron') }}"
    ## variables defining where the configurations are stored on the machine running the playbook
    host_config: "{{ host_config | default('{{ ansible_env.HOME }}/host.config.yml') }}"
    host_configs_dir: "{{ host_configs_dir | default('{{ ansible_env.HOME }}/configs') }}"
    ## installation feature options for the installed volttron platform
    messagebus: "{{ messagebus | default('zmq') }}"
    ##TODO: these all need to have defaults
    enable_web: no
    enable_drivers: yes
    extra_requirements: "{{ extra_requirements | default([]) }}"
    http_proxy: ''
    my_ansible_vitualenv: "{{ my_ansible_vitualenv | default('{{ansible_env.HOME }}/ansible_venv') }}"
    my_ansible_python_interpreter: "{{ my_ansible_vitualenv | default('{{ansible_env.HOME }}/ansible_venv')}}/bin/python"
