---
- name: Set default values
  set_fact:
    ansible_python_interpreter: /usr/bin/python3
    ## variables related to the version of volttron to be installed
    volttron_git_organization: "{{ volttron_git_organization | default('volttron') }}"
    volttron_git_repo: "{{ volttron_git_repo | default('volttron') }}"
    volttron_git_branch: "{{ volttron_git_branch | default('develop') }}"
    ## variables related to where volttron source and state are placed on the node
    volttron_home: "{{ volttron_home | default('{{ ansible_env.HOME }}/.volttron') }}"
    volttron_root: "{{ volttron_root | default('{{ ansible_env.HOME }}/volttron') }}"
    ## variables configuring where to look to find the platform configuration to deploy
    ## variables defining where the platform configuration lands on the remote
    host_config: "{{ host_config | default('{{ ansible_env.HOME }}/host.config.yml') }}"
    host_configs_dir: "{{ host_configs_dir | default('{{ ansible_env.HOME }}/configs') }}"
    ## installation feature options for the installed volttron platform
    messagebus: "{{ messagebus | default('zmq') }}"
    ##TODO: these all need to have defaults
    enable_web: no
    enable_drivers: yes
    extra_requirements: "{{ extra_requirements | default([]) }}"
    http_proxy: ''
    my_ansible_vitualenv: "{{ my_ansible_vitualenv | default('{{ansible_env.HOME }}/ansible_venv') }}"
    my_ansible_python_interpreter: "{{ my_ansible_vitualenv | default('{{ansible_env.HOME }}/ansible_venv')}}/bin/python"
## these facts must be set in separate tasks because they build on each other
## NOTE: ansible does not consider paths relative to CWD, these paths must be absolute
- set_fact:
    # absolute path to configurations directory for all deployments in inventory
    deployment_config_root: "{{ deployment_config_root | default( lookup('env', 'DEPLOYMENT_ROOT') ) }}"
- set_fact:
    # absolute path to configurations directory specific to this node in the inventory
    deployment_host_config_dir: "{{ deployment_host_config_dir | default( deployment_config_root + '/' + inventory_hostname ) }}"
- set_fact:
    # absolute path to the agent configurations directory specific to this node
    deployment_platform_config_dir: "{{ deployment_platform_config_dir | default( deployment_host_config_dir + '/' + '/configs') }}"
- set_fact:
    # absolute path to the platform configuration file for this node
    deployment_platform_config_file: "{{ deployment_platform_config_file | default( deployment_host_config_dir + '/' + inventory_hostname + '.yml' ) }}"
